[build]
  command = "npm install && npm run build && node node_modules/pug-cli/index.js views/ --out ./"
  functions = "functions"
[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/app/*"
  status = 200
  to = "/.netlify/functions/app/:splat"
